name: Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Checkout database
      uses: actions/checkout@v3
      with:
        path: database

    - name: Install dependencies for database
      working-directory: ./database
      run: |
        npm install

    - name: Export database as json
      working-directory: ./database
      run: |
        npm run generate-all
    
    - name: Checkout web
      uses: actions/checkout@v3
      with:
        repository: XeroAlpha/caidlistweb
        path: web

    - name: Install dependencies for web
      working-directory: ./web
      run: |
        yarn install

    - name: Copy files
      run: |
        cp -r ./database/output/web ./web/public/data
        cp ./database/output/web/index.json ./web/src/assets/dataIndex.json

    - name: Build web
      working-directory: ./web
      run: |
        yarn build

    - name: Deploy to self-hosted site
      run: |
        cd ./web/dist/
        tar -cvzf ../../idlist.tar.gz *
        cd ../..
        echo "${{ secrets.SSH_KEY }}" > key.txt
        chmod 400 key.txt
        scp -pqrO -P ${{ secrets.PORT }} -o StrictHostKeyChecking=no -i key.txt ./idlist.tar.gz "${{ secrets.USERNAME }}"@"${{ secrets.HOST }}":${{ secrets.TARGET_PATH }}/idlist.tar.gz
        ssh -q -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no -i key.txt "${{ secrets.USERNAME }}"@"${{ secrets.HOST }}" "cd ${{ secrets.TARGET_PATH }} && tar -xvzf ./idlist.tar.gz && rm ./idlist.tar.gz"
        rm key.txt

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact to GitHub pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: './web/dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
